load("@rules_cc//cc:objc_library.bzl", "objc_library")

objc_library(
    name = "LocalizedString",
    hdrs = [
        "Public/Foundation/GTMLocalizedString.h",
    ],
    includes = [
        "Public/Foundation",
    ],
    visibility = ["//visibility:public"],
)
